# Generated by Django 2.0.5 on 2018-10-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothFitting',
            fields=[
                ('cloth_fitting_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_fitting_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClothPrint',
            fields=[
                ('cloth_Print_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_Print_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClothSize',
            fields=[
                ('cloth_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_size_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('cloth_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('cloth_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_sku_no', models.CharField(max_length=50)),
                ('product_title', models.CharField(max_length=200)),
                ('product_unit_price', models.FloatField()),
                ('product_selling_price', models.FloatField()),
                ('product_description', models.CharField(max_length=500)),
                ('product_clothes_print_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ClothPrint')),
                ('product_clothes_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ClothType')),
                ('product_color', models.ManyToManyField(blank=True, related_name='products', to='products.Color')),
                ('product_fitting', models.ManyToManyField(blank=True, related_name='products', to='products.ClothFitting')),
            ],
        ),
        migrations.CreateModel(
            name='ShirtSleeves',
            fields=[
                ('shirt_sleeves_id', models.AutoField(primary_key=True, serialize=False)),
                ('shirt_sleeves_Type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='products.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_shirt_sleeve_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ShirtSleeves'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ClothSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.SubCategory'),
        ),
    ]
