# Generated by Django 2.0.5 on 2018-10-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('product_rating_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('product_review_text', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('product_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_review_text', models.CharField(max_length=250)),
            ],
        ),
    ]
