# Generated by Django 2.0.5 on 2018-10-31 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_productrating_productreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_ratings', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_reviews', to='products.Product')),
                ('product_review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_reviews', to='products.ProductReview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='productrating',
            old_name='product_review_text',
            new_name='product_rating_text',
        ),
        migrations.AddField(
            model_name='customerproductrating',
            name='product_rating_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_ratings', to='products.ProductRating'),
        ),
        migrations.AddField(
            model_name='customerproductrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_product_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customerproductreview',
            unique_together={('product_review_id', 'product_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='customerproductrating',
            unique_together={('product_rating_id', 'product_id', 'user')},
        ),
    ]
