# Generated by Django 2.0.5 on 2018-11-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181031_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.BinaryField(blank=True),
        ),
    ]
