# Generated by Django 2.0.5 on 2018-11-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_collartype_materialtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_collar_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.CollarType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_material_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.MaterialType'),
            preserve_default=False,
        ),
    ]
