# Generated by Django 2.0.5 on 2018-11-03 15:35

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_auto_20181101_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='customerproductrating',
            unique_together={('product_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='customerproductreview',
            unique_together={('product_id', 'user')},
        ),
    ]
