# Generated by Django 2.0.5 on 2018-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181103_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_average_rating',
            field=models.FloatField(default=0),
        ),
    ]
