# Generated by Django 2.0.5 on 2019-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
