# Generated by Django 2.0.5 on 2019-02-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_product_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_view_count',
        ),
    ]
