# Generated by Django 2.0.5 on 2019-02-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_remove_shoppingcart_timestamp2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartentry',
            name='cart',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='shoping_cart_entry', to='shopping_cart.ShoppingCart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcartentry',
            name='product',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='shoping_cart_entry', to='products.Product'),
            preserve_default=False,
        ),
    ]
